web:
  build: .
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - ./src:/var/www/diamante
  links:
    - db
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: '123123'
    MYSQL_USER: diamantedesk
    MYSQL_PASSWORD: '123123'
    MYSQL_DATABASE: diamantedesk
